version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci

  build:
    commands:
      - echo "Building Vite app..."
      - npm run build

  post_build:
    commands:
      - echo "Distribution ID is: $CLOUDFRONT_DIST_ID"
      - echo "Creating CloudFront invalidation..."
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths "/index.html"

artifacts:
  base-directory: dist
  files:
    - "**/*"
